   //App
   export const APP_RESTORE_COMPONENT = 'APP_RESTORE_COMPONENT'
   export const APPBANNERGET = 'APPBANNERGET'
   export const FETCHUSERINFO_SUCCESS = 'FETCHUSERINFO_SUCCESS'
   export const FETCHBANNER_SUCCESS = 'FETCHBANNER_SUCCESS'
   export const FETCHSALSE_SUCCESS = 'FETCHSALSE_SUCCESS'
   export const FETCHCATELIST_SUCCESS = 'FETCHCATELIST_SUCCESS'
   export const FETCHCATEGOODS_SUCCESS = 'FETCHCATEGOODS_SUCCESS'
   export const UPDATE_CATEID_STATUS = 'UPDATE_CATEID_STATUS'
   export const UPDATE_PULLUP_STATUS = 'UPDATE_PULLUP_STATUS'
   export const UPDATE_LIEVENT_STATUS = 'UPDATE_LIEVENT_STATUS'


   //Search

   export const MSG_LIST_PAGE_TRY_RESTORE_COMPONENT = 'MSG_LIST_PAGE_TRY_RESTORE_COMPONENT'
   export const MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS = 'MSG_LIST_PAGE_FETCH_ITEMS_SUCCESS'
   export const MSG_LIST_PAGE_FETCH_ITEMS_FAIL = 'MSG_LIST_PAGE_FETCH_ITEMS_FAIL'
   export const MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS = 'MSG_LIST_PAGE_UPDATE_PULLDOWN_STATUS'
   export const MSG_LIST_PAGE_UPDATE_PULLUP_STATUS = 'MSG_LIST_PAGE_UPDATE_PULLUP_STATUS'
   export const MSG_LIST_UPDATE_SEARCHNUM = 'MSG_LIST_UPDATE_SEARCHNUM'
   export const MSG_LIST_PAGE_BACKUP_ISCROLL_Y = 'MSG_LIST_PAGE_BACKUP_ISCROLL_Y'
   export const MSG_LIST_PAGE_KEYWORD = 'MSG_LIST_PAGE_KEYWORD'
   export const MSG_LIST_PAGE_VOLUME = 'MSG_LIST_PAGE_VOLUME'
   export const MSG_LIST_PAGE_PRICE = 'MSG_LIST_PAGE_PRICE'
   export const MSG_LIST_PAGE_CATE_ID = 'MSG_LIST_PAGE_CATE_ID'

   export const MSG_LIST_PAGE_UPDATE_LOADING_STATUS = 'MSG_LIST_PAGE_UPDATE_LOADING_STATUS'

   //List


   export const LIST_RESTORE_COMPONENT = 'LIST_RESTORE_COMPONENT'
   export const LIST_NAV_SUCCESS = 'LIST_NAV_ITEMS_SUCCESS'
   export const LIST_NAV_FAIL = 'LIST_NAV_FAIL'
   export const LIST_GOODS_SUCCESS = 'LIST_GOODS_SUCCESS'
   export const LIST_GOODS_FAIL = 'LIST_GOODS_FAIL'
   export const LIST_GOODS_UPDATE_CHANGE_STATUS = 'LIST_GOODS_UPDATE_CHANGE_STATUS'
   export const LIST_UPDATE_LOADING_STATUS = 'LIST_UPDATE_LOADING_STATUS'
   export const LIST_BACKUP_Y = 'LIST_BACKUP_Y'



   //Detail
   export const DETAIL_INIT = 'DETAIL_INIT'
   export const DETAIL_RESTORE_COMPONENT = 'DETAIL_RESTORE_COMPONENT'
   export const DETAIL_GOODS_SUCCESS = 'DETAIL_GOODS_SUCCESS'
   export const DETAIL_PROPS_SUCCESS = 'DETAIL_PROPS_SUCCESS'
   export const DETAIL_PROPS_FAIL = 'DETAIL_PROPS_FAIL'


   export const DETAIL_GOODS_FAIL = 'DETAIL_GOODS_FAIL'
   export const DETAIL_UPDATE_LOADING_STATUS = 'DETAIL_UPDATE_LOADING_STATUS'
   export const DETAIL_ID_STATUS = 'DETAIL_ID_STATUS'
   export const DETAIL_UPDATA_LOCALDETAILDATA = 'DETAIL_UPDATA_LOCALDETAILDATA'
   export const DETAIL_UPDATA_ID = 'DETAIL_UPDATA_ID'


   //HOME
   export const INFO_RESTORE_COMPONENT = 'INFO_RESTORE_COMPONENT'
   export const INFO_GOODS_SUCCESS = 'INFO_GOODS_SUCCESS'
   export const INFO_GOODS_FAIL = 'INFO_GOODS_FAIL'
   export const HOME_UPDATE_LOADING_STATUS = 'HOME_UPDATE_LOADING_STATUS'
   export const HOME_BACKUP_Y = 'HOME_BACKUP_Y'


   //Log

   export const LOG_RESTORE_COMPONENT = 'LOG_RESTORE_COMPONENT'
   export const LOG_GOODS_SUCCESS = 'LOG_GOODS_SUCCESS'
   export const LOG_GOODS_FAIL = 'LOG_GOODS_FAIL'
   export const LOG_UPDATE_LOADING_STATUS = 'LOG_UPDATE_LOADING_STATUS'
   export const LOG_BACKUP_Y = 'LOG_BACKUP_Y'

//AllORDER

   export const ALLORDER_RESTORE_COMPONENT = 'ALLORDER_RESTORE_COMPONENT'
   export const ALLORDER_GOODS_SUCCESS = 'ALLORDER_GOODS_SUCCESS'
   export const ALLORDER_GOODS_FAIL = 'ALLORDER_GOODS_FAIL'
   export const ALLORDER_UPDATE_LOADING_STATUS = 'ALLORDER_UPDATE_LOADING_STATUS'
   export const ALLORDER_BACKUP_Y = 'ALLORDER_BACKUP_Y'
   export const ALLORDER_UPDATE_CATEID_STATUS = 'ALLORDER_UPDATE_CATEID_STATUS'
   export const ALLORDER_UPDATE_PULLUP_STATUS = 'ALLORDER_UPDATE_PULLUP_STATUS'